### ISSUE TITLE
访客详情页面分享的链接提供手机号输入框，输入以后显示对应人员的访客证

### ISSUE THREAD

**Issue by ajaxjiang96** [tusdesign/standalone-html#3]
https://www.figma.com/proto/9yEmYVsurkVqf9bOGZSpKj/App?page-id=0%3A1&node-id=525%3A3868&viewport=1381%2C-1721%2C0.54&scaling=scale-down&starting-point-node-id=525%3A3868&show-proto-sidebar=1

**Comment by AmyJiangWenyan** [comment]
1

**Comment by AmyJiangWenyan** [comment]
verified, open new tickets
